module.exports = {
  api_url: 'https://api.vk.com/method/',
  access_token: '',
  user_id: 0,
  group_id: -0,
  api_version: 5.101,
  max_wall_requests: 5000,
  first_initial_count: 10,
  request_count: 3,
  enable_hours: [],
  not_force_delay: 600000,
  disable_hours: [],
  telegram_api_url: 'https://api.telegram.org/bot:/',
  telegram_chat_id: 0,
  telegram_delay: 60 * 60 * 1000,
};
